### ISSUE TITLE
Idea: include somewhere the Kernel Adiutor profile and / or direct thermal engine kernel settings for the module to work properly

### ISSUE THREAD

**Issue by crok** [TheHitMan7/Mido-OptimizedThermalEngine#1]
Hi,

I want to say thank you for the thermal-conf, looks really promising for us, Mido users!
I just would like to share an idea with you:
If I were you I would share the Kernel Adiutor profile in the module description
to enable MSM Thermal engine easily during boot time ([here it is](https://gist.github.com/crok/0255ec829fd0aea727fd594ad5b03780#file-ka_mido_enable_msm_thermal-json))
 _- or -_
include the following in service.sh and let Magisk to do it during boot:
```
echo 0 > /sys/module/msm_thermal/core_control/enabled
echo 0 > /sys/module/msm_thermal/vdd_restriction/enabled
echo Y > /sys/module/msm_thermal/parameters/enabled
```

Have a nice day!

**Comment by TheHitMan7** [comment]
Hi there,

Thanks for the idea and i am already looking into it. I will push these desired changes in post-fs-data.sh file. All these configurations will load at boot. So users don't have to do additional things.
