### ISSUE TITLE
Testing on MIUI

### ISSUE THREAD

**Issue by crok** [TheHitMan7/Mido-OptimizedThermalEngine#2]
Hi there,

I installed the module immediately when I saw it's been approved  ( :

I am using a MIUI ROM at the moment (Xiaomi.EU stable V10.2.2.0 Nougat) and really keen to test it.

The module put the thermal-engine.conf in the /vendor/etc directory because the function called system_thermal_engine that looks for the existence of /system/bin/thermal-engine found nothing and thus the script decides to remove the thermal-engine.conf to be installed to /system/etc and the other function found the thermal-engine in /vendor/bin thus it does not delete it to be installed to /vendor/etc.

I found a thermal-engine.conf in the /system/etc dir and I think this is the correct place for MIUI - but not sure, that's why I'm asking (other Xiaomi phones running on Nougat have it in /system/etc).

So comes the question:
Which one is the correct place for thermal-engine.conf on MIUI?
/system/etc   or   /vendor/etc
Does that hurt anything if magic mount it to both places?

**Comment by TheHitMan7** [comment]
As much as i am concerned with this, MIUI has thermal binary in "/system/bin" and the thermal config file in "/system/etc". It is there for a reason. Since in MIUI thermal binary read thermal config file from "/system/etc" and in LOS/Aosp roms it is different, the thermal binary in "/vendor/bin" and config in "vendor/etc".

This part of code defines the exact place of thermal binary before installing thermal config.

```
# dependencies
SYSTEM_THERMAL="/system/bin/thermal-engine"
VENDOR_THERMAL="/vendor/bin/thermal-engine"
```

Depend on above statement below code works.

```
# main
system_thermal_engine() {
if [ -e "$SYSTEM_THERMAL" ] ; then
    echo "- System thermal found continue..."
else
    echo "- System thermal not found !"
    busybox rm -rf $MODPATH/system/etc/thermal-engine.conf
fi
}

vendor_thermal_engine() {
if [ -e "$VENDOR_THERMAL" ] ; then
    echo "- Vendor thermal found continue..."
else
    echo "- Vendor thermal not found !"
    busybox rm -rf $MODPATH/system/vendor/etc/thermal-engine.conf
fi
}
```

You can double check in MIUI, where it is placed and i will update the module with relevant configurations.

**Comment by crok** [comment]
Got it!


My concern is that

system_thermal_engine function checks
if /system/bin/thermal-engine file exists then
if it exists it deletes the file in $MODPATH/system/etc/thermal-engine.conf
and thus effectively only /**vendor**/etc/thermal-engine.conf will be installed

and

vendor_thermal_engine function checks
if /vendor/bin/thermal-engine file exists then
if it exists it deletes the file in $MODPATH/system/vendor/etc/thermal-engine.conf
and thus effectively only /system/etc/thermal-engine.conf will be installed

This is what I read from the script and this is what I experience too when use the Module.


Shouldn't it work the opposite way around?


If /system/bin/thermal-engine file exists then
if it exists it should delete the file in $MODPATH/system/**vendor**/etc/thermal-engine.conf
and thus effectively /system/etc/thermal-engine.conf will be installed

and

if /**vendor**/bin/thermal-engine file exists then
if it exists it should delete the file in $MODPATH/system/etc/thermal-engine.conf
and thus effectively /**vendor**/etc/thermal-engine.conf will be installed

**Comment by crok** [comment]
Got it!
